export const LIST_USER_REGISTERED_REQUEST = "@userREGISTERED/LIST_USER_REGISTERED_REQUEST";
export const LIST_USER_REGISTERED_SUCCESS = "@userREGISTERED/LIST_USER_REGISTERED_SUCCESS";
export const LIST_USER_REGISTERED_FAILED = "@userREGISTERED/LIST_USER_REGISTERED_FAILED";

export const GET_KEYWORD = "@search/GET_KEYWORD";
