export const DETAIL_CATEGORY_REQUEST = "@detailCate/DETAIL_CATEGORY_REQUEST"
export const DETAIL_CATEGORY_SUCCESS = "@detailCate/DETAIL_CATEGORY_SUCCESS"
export const DETAIL_CATEGORY_FAILED = "@detailCate/DETAIL_CATEGORY_FAILED"