export const LIST_WAIT_APPROVAL_REQUEST = "@userapproval/LIST_WAIT_APPROVAL_REQUEST";
export const LIST_WAIT_APPROVAL_SUCCESS = "@userapproval/LIST_WAIT_APPROVAL_SUCCESS";
export const LIST_WAIT_APPROVAL_FAILED = "@userapproval/LIST_WAIT_APPROVAL_FAILED";

export const GET_KEYWORD = "@search/GET_KEYWORD";
