export const LIST_COURSE_REGISTERED_REQUEST = "@courseregistered/LIST_COURSE_REGISTERED_REQUEST";
export const LIST_COURSE_REGISTERED_SUCCESS = "@courseregistered/LIST_COURSE_REGISTERED_SUCCESS";
export const LIST_COURSE_REGISTERED_FAILED = "@courseregistered/LIST_COURSE_REGISTERED_FAILED";

export const GET_KEYWORD = "@search/GET_KEYWORD";
