export const RENDER_COURSES_REQUEST = "@courses/RENDER_COURSES_REQUEST"
export const RENDER_COURSES_SUCCESS = "@courses/RENDER_COURSES_SUCCESS" 
export const RENDER_COURSES_FAILED = "@courses/RENDER_COURSES_FAILED"  
