export const RENDER_LIST_COURSES_REQUEST =
  "@courses/RENDER_LIST_COURSES_REQUEST";
export const RENDER_LIST_COURSES_SUCCESS =
  "@courses/RENDER_LIST_COURSES_SUCCESS";
export const RENDER_LIST_COURSES_FAILED = "@courses/RENDER_LIST_COURSES_FAILED";