export const RENDER_COURSES_REQUEST = "@allCourse/RENDER_COURSES_REQUEST";
export const RENDER_COURSES_SUCCESS = "@allCourse/RENDER_COURSES_SUCCESS";
export const RENDER_COURSES_FAILED = "@allCourse/RENDER_COURSES_FAILED";